### ISSUE TITLE
stream faders doesn't respond

### ISSUE THREAD

**Issue by mornja** [fu-raz/midi-mixer-wavelink-new#1]
first of all, thanks for working on this!

I see that when you connect a fader to a monitor channel, it works fine, but not for stream channels (. The mute button woks fine for stream, though.

Here is the output that doesn't result in any fader movement. However, the value does change correctly based on fader position - just no response seen in wave link.

Sending: {"jsonrpc":"2.0","method":"setInputConfig","id":64,"params":
{"property":"Volume","identifier":"AS42J1A01869\\PCM_IN_01_C_00_SD1","mixerID":"com.elgato.mix.stream","value":10,"forceLink":false}}

 It also works fine when switching monitor outputs.

**Comment by fu-raz** [comment]
Could you try the new version [#v0.0.7](https://github.com/fu-raz/midi-mixer-wavelink-new/releases/tag/v0.0.7)? I believe this update fixes this problem

**Comment by fu-raz** [comment]
Also, which version of Wavelink are you using? This might be important as well :) I'm using v1.6.0.2990

**Comment by mornja** [comment]
I tested the new version, but the issue is the same.  I am using version 1.6.0.2990.

**Comment by fu-raz** [comment]
Thank you for testing this with me. It is really strange though. Because I can't seem to reproduce the problem. I really thought that adding the delay would fix the problem. Could you answer a few more questions to see if we can get to the bottom of this?

1. Which device are you using? I'm using a Behringer X Touch mini myself, but it only has one fader. I tried to set the fader to a stream channel and it still worked.
2. None of the stream channels work for you, correct? Not just the one in the example you sent?
3. Do you see no movement at all in the wavelink stream slider or does it jitter? Kind of like it wants to set the new value but jumps back?
4. Do you have the sliders linked? 
5. Does changing the stream slider in WaveLink change the fader of your device (so the other way around)?
6. And if it works that way, could you check which mixerID is used in the message that is received?

![image](https://user-images.githubusercontent.com/5355154/204790714-ce55f457-a1ec-447c-853f-e4183a1dd166.png)

If you see the correct change in value in the RPC messages it means that the part in MIDI Mixer works correctly. But if Wavelink doesn't show any change in the sliders, that means it isn't responding to the setInputConfig command. The monitor and stream commands are identical apart from the mixerID. Which would be `com.elgato.mix.monitor` or `com.elgato.mix.stream`. So my guess is that somehow with your setup this is incorrect.

**Comment by mornja** [comment]
1. NanoKontrol2 by Korg
2. That is correct. The stream channels do not work. Here is an image showing what happens for the monitor (the first ones) and the stream (the last ones).
![image](https://user-images.githubusercontent.com/96291107/204883874-b3b92fde-9537-4a3b-8e60-8a564e21f6e8.png)
3. There is no jitter in wave link.  BUT the mute-buttons work as they should! Actually, I can't move the stream faders in wavelink at all. they are frozen in place (but only when unlinked)
4. The sliders are unlinked. However, there is some strange behavior in wavelink when linking and moving the stream slider. What happens then is that by just moving the stream slider a bit, the monitor slider moves in very big increments. basically, just a few "clicks" down on the stream slider moves the monitor to the lowest position.
5. No, but the nanokontrol does not have automated faders - but, for some reason, i cannot move the stream sliders at all in the wavelink they won't move at all when connected to midimixer.
6.  I can't move the fader in wavelink, but here is what appears in the developer display when i press mute on any of the added stream channels
![image](https://user-images.githubusercontent.com/96291107/204886494-0d655ff2-d8d4-44ea-b4ab-6c5bce1a12c2.png)

**Comment by mornja** [comment]
hope this helps. and also, thank you for working on this. it is very much apprechated.

**Comment by fu-raz** [comment]
Thank you for the extensive report! Great to hear my work is appreciated. I didn't plan on actually working on this plugin at first tbh. Just wanted to help Anais out with the new client. But then I started to have fun, and now here we are. 

So what I initially thought clearly isn't the case. The mixerID is the right one, since the mute button works. I could've known because you already said this in your first post. What is strange to me is the behavior of wavelink when you have midi mixer connected. It sounds like the sliders in Wavelink can't move because the faders of the nanokontrol aren't automated. And because the fader isn't moving, the plugin sends back the value it already had. Although that would mean that it also wouldn't work for the monitor parts. So that makes me think that maybe another application is forcing the stream channel. Could it be that another application, like a streamdeck, is interfering?

Just to be sure I ordered a nanoKontrol2 myself. It should arrive this weekend, so I might be able to find out what's wrong. I was planning on getting another midi controller anyway and they had the nanokontrol in white. I see they also have a solo button so I can actually use the solo button feature I added. What does the R button normally do?

**Comment by DrMicka** [comment]
Hello,
I would like try you plugin with my DIY streamDeck.
I Downloaded your folder and I put here %appdata%\midi-mixer-app\plugins
I see your plugin but when I click on activate, nothing happens and it stays in deactivated (the button does not change to activated)
Thank you for your help, maybe I can help you later

**Comment by fu-raz** [comment]
@DrMicka I made a new issue for you, cause your problem hasn't got much to do with the fader issue Please check https://github.com/fu-raz/midi-mixer-wavelink-new/issues/2

**Comment by fu-raz** [comment]
So my nanoKontrol2 arrived today, so I'll be testing out the plugin a.s.a.p.

**Comment by fu-raz** [comment]
@mornja I hope you're still following this thread. I just received the nanoKONTROL2 and got it working. The problem however is that I didn't do anything to make it work. It just worked out of the box. 

I did have to install KORG KONTROL Editor to make the LEDs work. So from what I've seen so far it looks like the problem you're having is system specific. Could you maybe check if you have other software running like a streamdeck or other software that control the WaveLink. Otherwise maybe try resetting the device (https://youtu.be/zCvaq0J-xuU?t=23)

I found a very useful thread in the MIDI Mixer discord here:
https://discord.com/channels/727865704644214844/776485644150505534/850322257443422220

**Comment by mornja** [comment]
Hi! Yes, I'm back. Hope you enjoy the nanokontrol2. neat device. 

Hm... 

I did change the korg kontrol as well to get the mute lights to work. Can't remember the parameter, but was one setting I had to change.

I did unplug my streamdeck, and force quit the app. but the same thing. no response on the faders for stream. Did restart the various apps as well.

I will now install latest version of wavelink and see what happens.

**Comment by mornja** [comment]
alright! got it to work, finally.  i think i narrowed it down to some issue with the virtual stream output - it may have been corrupted by another virtual cable I had installed - so i removed everything, including midimixer, restarted a few times, changed the usb port on my elgato-mic - and bingo! so, now it works very well. super.

**Comment by fu-raz** [comment]
Glad you got it working as well. If you have any ideas or suggestions for the plugin let me know!

**Comment by mornja** [comment]
thanks again for your work here. this is very beneficial to my daily life, so very grateful.

 a suggestion, and perhaps it is already possible to implement by making a custom profile? That is, using for example the S button to mute the rotory control. now, you can only mute the sliders. 

this way, it would be possible to have slider be monitor output, and you could use rotory over for stream. then mute slider with M and rotory with S.  Though, this is probably not something most people would need - but wonder if it is technically possible.
